version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - myNetwork
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    networks:
      - myNetwork
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
networks:
  myNetwork:
    driver: bridge