version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    networks:
      - myNetwork
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: db
    networks:
      - myNetwork
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_USER: ${DB_ROOT_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
    container_name: phpmyadmin
    depends_on:
       - db
    ports:
       - "8081:80"
networks:
  myNetwork:
    driver: bridge