// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	types "gotest/types"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateNewuser provides a mock function with given fields: user
func (_m *UserRepository) CreateNewuser(user types.User) types.User {
	ret := _m.Called(user)

	var r0 types.User
	if rf, ok := ret.Get(0).(func(types.User) types.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(types.User)
	}

	return r0
}

// DeleteUserByName provides a mock function with given fields: username
func (_m *UserRepository) DeleteUserByName(username string) error {
	ret := _m.Called(username)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserByUsernameAndPassword provides a mock function with given fields: username, password
func (_m *UserRepository) FindUserByUsernameAndPassword(username string, password string) (types.User, error) {
	ret := _m.Called(username, password)

	var r0 types.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (types.User, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) types.User); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(types.User)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUsers provides a mock function with given fields:
func (_m *UserRepository) GetAllUsers() []types.User {
	ret := _m.Called()

	var r0 []types.User
	if rf, ok := ret.Get(0).(func() []types.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.User)
		}
	}

	return r0
}

// GetUserByUsername provides a mock function with given fields: username
func (_m *UserRepository) GetUserByUsername(username string) (types.User, error) {
	ret := _m.Called(username)

	var r0 types.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (types.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) types.User); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(types.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: updatedUser
func (_m *UserRepository) UpdateUser(updatedUser types.User) (types.User, error) {
	ret := _m.Called(updatedUser)

	var r0 types.User
	var r1 error
	if rf, ok := ret.Get(0).(func(types.User) (types.User, error)); ok {
		return rf(updatedUser)
	}
	if rf, ok := ret.Get(0).(func(types.User) types.User); ok {
		r0 = rf(updatedUser)
	} else {
		r0 = ret.Get(0).(types.User)
	}

	if rf, ok := ret.Get(1).(func(types.User) error); ok {
		r1 = rf(updatedUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
